language: generic

dist: trusty
sudo: required

git:
  depth: 3

# prune $PATH to fix python3 (github.com/travis-ci/travis-ci/issues/5326)
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
  - python3 --version
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install -qq python3-gmpy2

script:
  - ./run-tests

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
