language: python

dist: trusty
sudo: required

python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

git:
  depth: 3

install:
  - sudo apt-get install -qq libmpfr-dev libmpc-dev
  - pip3 install gmpy2

script:
  - ./run-tests

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
